# Generated by Django 5.2.7 on 2026-02-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(default='Sin Titulo', max_length=100),
            preserve_default=False,
        ),
    ]
