# Generated by Django 5.2.7 on 2026-02-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_actividad_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
