# Generated by Django 5.2.7 on 2026-02-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_actividad_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='titulo',
        ),
    ]
